import { Inter, Gluten, ABeeZee } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const gluten = Gluten({ subsets: ["latin"] });
const abeezee = ABeeZee({ 
  subsets: ["latin"],
  weight: '400'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={abeezee.className}>{children}</body>
    </html>
  );
}
